---
output-file: 16-blood_tests.html
title: 16-blood_tests

---

# 16 - blood tests

The lab tests in this data set of the Human Phenotype Project are based on tests performed to participants in the community as part of their regular medical care at their HMO (Health Maintenance Organization). Participants are asked to upload their blood/urine tests done at their HMOs from previous years. These tests range from the very common CBC and chemistry tests, Vitamins levels to the standard PCRs for infectious diseases all the way to rare tests requiring the user to measure urine for 24h.

The information is stored in 1 parquet file `blood_tests.parquet`.

In [1]:
#| hide
import pandas as pd
pd.set_option('display.max_rows', 500)

In [2]:
from pheno_utils import PhenoLoader

In [3]:
dl = PhenoLoader('blood_tests', age_sex_dataset=None)
dl

DataLoader for blood_tests with
65 fields
1 tables: ['blood_tests']

In [4]:
dl.dict

,field_string,description_string,parent_dataframe,relative_location,value_type,units,sampling_rate,item_type,array,cohorts,data_type,debut,pandas_dtype
tabular_field_name,,,,,,,,,,,,,
hmo,HMO,One of 4 Isreali HMOs,NaN,blood_tests.parquet,Categorical (multiple),None,NaN,tabular,Single,10K,NaN,2015-01-01,category
collection_date,Collection date,Collection date,NaN,blood_tests.parquet,Time,None,NaN,tabular,Single,10K,NaN,2015-01-01,datetime64[ns]
bt__albumin_float_value,Blood test - Albumin (Numerical),Albumin,NaN,blood_tests.parquet,Continuous,g/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__alkaline_phosphatase_float_value,Blood test - Alkaline Phosphatase (Numerical),ALKP - Alkaline Phosphatase,NaN,blood_tests.parquet,Continuous,u/l,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__alt_float_value,Blood test - ALT (Numerical),ALT (GPT) - Alanine Aminotransferease,NaN,blood_tests.parquet,Continuous,u/l,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__ast_float_value,Blood test - AST (Numerical),AST (GOT) - Aspartate Aminotransferase,NaN,blood_tests.parquet,Continuous,u/l,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__basophils_%_float_value,Blood test - Basophils % (Numerical),Baso % - Basophils percent,NaN,blood_tests.parquet,Continuous,%,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__basophils_abs_float_value,Blood test - Basophils # (Numerical),Baso # - Basophils absolute,NaN,blood_tests.parquet,Continuous,k/ul,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__calcium_float_value,Blood test - Calcium (Numerical),Ca - Calcium,NaN,blood_tests.parquet,Continuous,mg/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__creatinine_float_value,Blood test - Creatinine (Numerical),Creatinine,NaN,blood_tests.parquet,Continuous,mg/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__direct_bilirubin_categorical_value,Blood test - Direct Bilirubin (Categorical),Bilirubin Direct/Conjugated,NaN,blood_tests.parquet,Categorical (multiple),None,NaN,tabular,Single,10K,NaN,2015-01-01,category
bt__direct_bilirubin_float_value,Blood test - Direct Bilirubin (Numerical),Bilirubin Direct/Conjugated,NaN,blood_tests.parquet,Continuous,mg/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__eosinophils_%_float_value,Blood test - Eosinophils % (Numerical),Eos % - eosinophils percent,NaN,blood_tests.parquet,Continuous,%,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__eosinophils_abs_float_value,Blood test - Eosinophils # (Numerical),Eos # - eosinophils absolute,NaN,blood_tests.parquet,Continuous,k/ul,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__estradiol_categorical_value,Blood test - Estradiol (Categorical),E2 - Estradiol,NaN,blood_tests.parquet,Categorical (multiple),None,NaN,tabular,Single,10K,NaN,2015-01-01,category
bt__estradiol_float_value,Blood test - Estradiol (Numerical),E2 - Estradiol,NaN,blood_tests.parquet,Continuous,pmol/l,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__ferritin_categorical_value,Blood test - Ferritin (Categorical),Ferritin,NaN,blood_tests.parquet,Categorical (multiple),None,NaN,tabular,Single,10K,NaN,2015-01-01,category
bt__ferritin_float_value,Blood test - Ferritin (Numerical),Ferritin,NaN,blood_tests.parquet,Continuous,ng/ml,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__ggt_float_value,Blood test - GGT (Numerical),GGT - gama-Glutamyl Transpeptidase,NaN,blood_tests.parquet,Continuous,u/l,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__glucose_float_value,Blood test - Glucose (Numerical),Glucose,NaN,blood_tests.parquet,Continuous,mg/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__hba1c_float_value,Blood test - HbA1C (Numerical),HbA1C %,NaN,blood_tests.parquet,Continuous,%,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__hdl_cholesterol_float_value,Blood test - HDL Cholesterol (Numerical),HDL Cholesterol,NaN,blood_tests.parquet,Continuous,mg/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__hematocrit_float_value,Blood test - Hematocrit (Numerical),HCT - Hematocrit,NaN,blood_tests.parquet,Continuous,%,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__hemoglobin_float_value,Blood test - Hemoglobin (Numerical),Hb - Hemoglobin,NaN,blood_tests.parquet,Continuous,g/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__ldl_cholesterol_float_value,Blood test - LDL Cholesterol (Numerical),LDL Cholesterol,NaN,blood_tests.parquet,Continuous,mg/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__lymphocytes_%_float_value,Blood test - Lymphocytes % (Numerical),Lymp % - Lymphocytes percent,NaN,blood_tests.parquet,Continuous,%,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__lymphocytes_abs_float_value,Blood test - Lymphocytes # (Numerical),Lymp # - Lymphocytes absolute,NaN,blood_tests.parquet,Continuous,k/ul,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__mch_float_value,Blood test - MCH (Numerical),MCH - Mean cell Hemoglobin,NaN,blood_tests.parquet,Continuous,pg/cell,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__mchc_float_value,Blood test - MCHC (Numerical),MCHC - Mean cell Hemoglobin concentration,NaN,blood_tests.parquet,Continuous,g/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__mcv_float_value,Blood test - MCV (Numerical),MCV - Mean Corpuscular Volume or Mean cell volume,NaN,blood_tests.parquet,Continuous,fl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__monocytes_%_float_value,Blood test - Monocytes % (Numerical),Mono % - Monoctypes percent,NaN,blood_tests.parquet,Continuous,%,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__monocytes_abs_float_value,Blood test - Monocytes # (Numerical),Mono % - Monoctypes absolute,NaN,blood_tests.parquet,Continuous,k/ul,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__mpv_float_value,Blood test - MPV (Numerical),MPV - Mean Platelet Volume,NaN,blood_tests.parquet,Continuous,fl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__neutrophils_%_float_value,Blood test - Neutrophils % (Numerical),Neut % - Neutrophils percent,NaN,blood_tests.parquet,Continuous,%,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__neutrophils_abs_float_value,Blood test - Neutrophils # (Numerical),Neut # - Neutrophils absolute,NaN,blood_tests.parquet,Continuous,k/ul,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__non_hdl_cholesterol_float_value,Blood test - Non HDL Cholesterol (Numerical),Non HDL Cholesterol,NaN,blood_tests.parquet,Continuous,mg/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__phosphore_float_value,Blood test - Phosphore (Numerical),P - Phosphore,NaN,blood_tests.parquet,Continuous,mg/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__platelets_float_value,Blood test - Platelets (Numerical),PLT - Platelets,NaN,blood_tests.parquet,Continuous,k/ul,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__potassium_float_value,Blood test - Potassium (Numerical),K+ - Potassium,NaN,blood_tests.parquet,Continuous,mmol/l,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__rbc_float_value,Blood test - RBC (Numerical),RBC - Red Blood Cells,NaN,blood_tests.parquet,Continuous,m/ul,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__rdw_float_value,Blood test - RDW (Numerical),RDW - Red Blood Cell Distribution Width,NaN,blood_tests.parquet,Continuous,%,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__rheumatoid_factor_categorical_value,Blood test - Rheumatoid Factor (Categorical),Rheumatoid Factor Quantit,NaN,blood_tests.parquet,Categorical (multiple),None,NaN,tabular,Single,10K,NaN,2015-01-01,category
bt__rheumatoid_factor_float_value,Blood test - Rheumatoid Factor (Numerical),Rheumatoid Factor Quantit,NaN,blood_tests.parquet,Continuous,iu/ml,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__sodium_float_value,Blood test - Sodium (Numerical),Na - Sodium,NaN,blood_tests.parquet,Continuous,mmol/l,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__testosterone_total_categorical_value,Blood test - Testosterone Total (Categorical),Total Testosterone,NaN,blood_tests.parquet,Categorical (multiple),None,NaN,tabular,Single,10K,NaN,2015-01-01,category
bt__testosterone_total_float_value,Blood test - Testosterone Total (Numerical),Total Testosterone,NaN,blood_tests.parquet,Continuous,nmol/l,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__total_bilirubin_categorical_value,Blood test - Total Bilirubin (Categorical),Total Billirubin,NaN,blood_tests.parquet,Categorical (multiple),None,NaN,tabular,Single,10K,NaN,2015-01-01,category
bt__total_bilirubin_float_value,Blood test - Total Bilirubin (Numerical),Total Billirubin,NaN,blood_tests.parquet,Continuous,mg/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__total_cholesterol_float_value,Blood test - Total Cholesterol (Numerical),Total Cholesterol,NaN,blood_tests.parquet,Continuous,mg/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__total_protein_float_value,Blood test - Total Protein (Numerical),Total Protien,NaN,blood_tests.parquet,Continuous,g/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__triglycerides_float_value,Blood test - Triglycerides (Numerical),Triglycerides,NaN,blood_tests.parquet,Continuous,mg/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__tsh_categorical_value,Blood test - TSH (Categorical),TSH - Thyroid-stimulating hormone,NaN,blood_tests.parquet,Categorical (multiple),None,NaN,tabular,Single,10K,NaN,2015-01-01,category
bt__tsh_float_value,Blood test - TSH (Numerical),TSH - Thyroid-stimulating hormone,NaN,blood_tests.parquet,Continuous,miu/l,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__urate_float_value,Blood test - Urate (Numerical),Urate / Uric Acid,NaN,blood_tests.parquet,Continuous,mg/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__urea_float_value,Blood test - Urea (Numerical),Urea,NaN,blood_tests.parquet,Continuous,mg/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__vitamin_b12_categorical_value,Blood test - Vitamin B12 (Categorical),Vitamin B12 - Cobalamin,NaN,blood_tests.parquet,Categorical (multiple),None,NaN,tabular,Single,10K,NaN,2015-01-01,category
bt__vitamin_b12_float_value,Blood test - Vitamin B12 (Numerical),Vitamin B12 - Cobalamin,NaN,blood_tests.parquet,Continuous,pg/ml,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__vitamin_d_categorical_value,Blood test - Vitamin D (Categorical),Vitamin D,NaN,blood_tests.parquet,Categorical (multiple),None,NaN,tabular,Single,10K,NaN,2015-01-01,category
bt__vitamin_d_float_value,Blood test - Vitamin D (Numerical),Vitamin D,NaN,blood_tests.parquet,Continuous,ng/ml,NaN,tabular,Single,10K,NaN,2015-01-01,float64
bt__wbc_float_value,Blood test - WBC (Numerical),WBC - White blood cells,NaN,blood_tests.parquet,Continuous,k/ul,NaN,tabular,Single,10K,NaN,2015-01-01,float64
urine__acr_categorical_value,Urine test - ACR (Categorical),ACR - Albumin / Creatinine Ratio,NaN,blood_tests.parquet,Categorical (multiple),None,NaN,tabular,Single,10K,NaN,2015-01-01,category
urine__acr_float_value,Urine test - ACR (Numerical),ACR - Albumin / Creatinine Ratio,NaN,blood_tests.parquet,Continuous,mg/g creatinine,NaN,tabular,Single,10K,NaN,2015-01-01,float64
urine__creatinine_float_value,Urine test - Creatinine (Numerical),Creatinine,NaN,blood_tests.parquet,Continuous,mg/dl,NaN,tabular,Single,10K,NaN,2015-01-01,float64
urine__microalbumin_categorical_value,Urine test - Microalbumin (Categorical),Microalbumin,NaN,blood_tests.parquet,Categorical (multiple),None,NaN,tabular,Single,10K,NaN,2015-01-01,category
urine__microalbumin_float_value,Urine test - Microalbumin (Numerical),Microalbumin,NaN,blood_tests.parquet,Continuous,mg/l,NaN,tabular,Single,10K,NaN,2015-01-01,float64