---
output-file: 001-events.html
title: 001-events
---

# Events dataset  

Events Informations of the Human Phenotype Project study participants contains information regarding participant visits and calls.


### Data availability:

- Information about sex, study_id, month and year of birth per participant, visits types and dates: `events.parquet`

In [1]:
#| echo: false
import pandas as pd
pd.set_option("display.max_rows", 500)

In [2]:
from pheno_utils import PhenoLoader

In [3]:
pl = PhenoLoader('events')
pl

PhenoLoader for events with
10 fields
1 tables: ['events']

# Data dictionary

In [4]:
pl.dict

,field_string,description_string,folder_id,feature_set,field_type,strata,data_coding,array,pandas_dtype,bulk_file_extension,relative_location,units,bulk_dictionary,sampling_rate,transformation,list_of_tags,stability,sexed,debut,completed
tabular_field_name,,,,,,,,,,,,,,,,,,,,
month_of_birth,Month of birth,Month of birth,1,events,Categorical (single),Primary,042_03,Single,category,NaN,events/events.parquet,NaN,NaN,NaN,NaN,NaN,Accruing,Both sexes,2019-01-01,NaN
year_of_birth,Year of birth,Year of birth,1,events,Integer,Primary,NaN,Single,int,NaN,events/events.parquet,NaN,NaN,NaN,NaN,NaN,Accruing,Both sexes,2019-01-01,NaN
sex,Sex,Sex,1,events,Categorical (single),Primary,9,Single,category,NaN,events/events.parquet,NaN,NaN,NaN,NaN,NaN,Accruing,Both sexes,2019-01-01,NaN
research_stage_type,Research stage type,The type of the research stage,1,events,Categorical (single),Primary,001_01,Single,category,NaN,events/events.parquet,NaN,NaN,NaN,NaN,NaN,Accruing,Both sexes,2019-01-01,NaN
visit_center,Visit center,The name of the assessment center,1,events,Categorical (single),Primary,001_02,Single,category,NaN,events/events.parquet,NaN,NaN,NaN,NaN,NaN,Accruing,Both sexes,2019-01-01,NaN
research_stage_timestamp,Timestamp of research stage,The timestamp of the research stage. For examp...,1,events,Datetime,Collection time,NaN,Single,"datetime64[ns, Asia/Jerusalem]",NaN,events/events.parquet,NaN,NaN,NaN,NaN,NaN,Accruing,Both sexes,2019-01-01,NaN
research_stage_date,Date of research stage,"The date of the research stage. For example, i...",1,events,Date,Collection time,NaN,Single,datetime64[ns],NaN,events/events.parquet,NaN,NaN,NaN,NaN,NaN,Accruing,Both sexes,2019-01-01,NaN
age_at_research_stage,Age at research stage,The age of the participant during the research...,1,events,Continuous,Primary,NaN,Single,float,NaN,events/events.parquet,NaN,NaN,NaN,NaN,NaN,Accruing,Both sexes,2019-01-01,NaN
study_id,Study ID,The study identifier,1,events,Categorical (single),Auxiliary,000_01,Single,category,NaN,events/events.parquet,NaN,NaN,NaN,NaN,NaN,Accruing,Both sexes,2019-01-01,NaN
timezone,Timezone,Timezone,1,events,Text,Collection time,NaN,Single,category,NaN,events/events.parquet,NaN,NaN,NaN,NaN,NaN,Accruing,Both sexes,2019-01-01,NaN