---
output-file: 018-medications.html
title: 018-medications
---

# Medications

The medication information collection in the Human Phenotype Project study is based on self reporting of medications usage via online and smartphone applications and collection by staff members by telephone or face-to-face interviews during follow-up. 

Self-report is when the participant reports the use of medication to the researcher. 
Having accurate and complete data on medication usage is essential to understanding the true impact of these medications on individuals' health. 

### Data availability:
During registration (sign up) to the study, participants are asked to report their regular medications online(autofill), selecting from a predefined drop-down list.
The information is stored in 1 parquet file: `medications.parquet`

In [1]:
#| echo: false
import pandas as pd
pd.set_option("display.max_rows", 500)

In [2]:
from pheno_utils import PhenoLoader

In [3]:
dl = PhenoLoader('medications')
dl

DataLoader for medications with
12 fields
2 tables: ['medications', 'age_sex']

# Data dictionary

In [4]:
dl.dict

,field_string,description_string,relative_location,value_type,units,sampling_rate,item_type,array,cohorts,data_type,debut,pandas_dtype,parent_dataframe
tabular_field_name,,,,,,,,,,,,,
collection_timestamp,Collection time,Collection time,medications/medications.parquet,NaN,NaN,NaN,Data,NaN,NaN,NaN,NaN,"datetime64[ns, Asia/Jerusalem]",NaN
collection_date,Collection date,Collection date,medications/medications.parquet,NaN,NaN,NaN,Data,NaN,NaN,NaN,NaN,datetime64[ns],NaN
timezone,Timezone,Timezone,medications/medications.parquet,NaN,NaN,NaN,Data,NaN,NaN,NaN,NaN,string,NaN
medication,Medication name,Medication name,medications/medications.parquet,NaN,NaN,NaN,Data,NaN,NaN,NaN,NaN,string,NaN
start_month,Start month,Start month of medication taking,medications/medications.parquet,NaN,NaN,NaN,Data,NaN,NaN,NaN,NaN,float64,NaN
start_year,Start year,Start year of medication taking,medications/medications.parquet,NaN,NaN,NaN,Data,NaN,NaN,NaN,NaN,float64,NaN
ahfs_code,AHFS code,AHFS code mapping to medication name,medications/medications.parquet,NaN,NaN,NaN,Data,NaN,NaN,NaN,NaN,string,NaN
atc_code,ATC code,ATC code mapping to medication name,medications/medications.parquet,NaN,NaN,NaN,Data,NaN,NaN,NaN,NaN,string,NaN
medication_heb,Medication hebrew name,Medication hebrew name,medications/medications.parquet,NaN,NaN,NaN,Data,NaN,NaN,NaN,NaN,string,NaN
medication_mapping,Medication mapping,Mapping to ATC codes,medications/medications.parquet,NaN,NaN,NaN,Bulk,NaN,NaN,NaN,NaN,string,NaN