---
output-file: 045-participant_relation.html
title: 045-participant_relation
---

# Participant relation dataset

### Description 

The Human Phenotype Project conducts comprehensive data collection through online surveys, where participants voluntarily provide information on various aspects influencing their health. This includes information about other participant's they are related to.

### Introduction

Coming soon

### Measurement protocol 
<!-- long measurment protocol for the data browser -->
A short online survey is used to track participants in the study who are related in some way.

### Data availability 
<!-- for the example notebooks -->
The information is stored in 1 parquet files: `participant_relation.parquet`.

### Summary of available data 
<!-- for the data browser -->
Coming soon

### Relevant links

* Pheno Knowledgebase: https://knowledgebase.pheno.ai/datasets/045-participant_relation.html
* Pheno Data Browser: https://pheno-demo-app.vercel.app/folder/45

In [1]:
#| echo: false
import pandas as pd
pd.set_option("display.max_rows", 500)

In [2]:
from pheno_utils import PhenoLoader

In [3]:
pl = PhenoLoader('participant_relation')
pl

PhenoLoader for participant_relation with
7 fields
2 tables: ['participant_relation', 'age_sex']

# Data dictionary

In [4]:
pl.dict

,folder_id,feature_set,field_string,bulk_file_extension,bulk_dictionary,description_string,field_type,data_coding,units,stability,sampling_rate,strata,sexed,array,list_of_tags,debut,completed,relative_location,pandas_dtype
tabular_field_name,,,,,,,,,,,,,,,,,,,
collection_timestamp,59,participant relation,Collection timestamp,NaN,NaN,Timestamp of measurements collection,Datetime,NaN,Time,Accruing,NaN,Collection time,Both sexes,Single,NaN,2019-02-05,NaN,participant_relation/participant_relation.parquet,"datetime64[ns, Asia/Jerusalem]"
collection_date,59,participant relation,Collection date,NaN,NaN,Date of measurments collection,Date,NaN,Time,Accruing,NaN,Collection time,Both sexes,Single,NaN,2019-02-05,NaN,participant_relation/participant_relation.parquet,datetime64[ns]
timezone,59,participant relation,Timezone,NaN,NaN,Timezone of the measurments,Text,NaN,NaN,Accruing,NaN,Collection time,Both sexes,Single,NaN,2019-02-05,NaN,participant_relation/participant_relation.parquet,category
relation_type,59,participant relation,relation_type,NaN,NaN,Type of relation to other participant,Categorical (single),045_01,NaN,Accruing,NaN,Primary,Both sexes,Single,NaN,2019-02-05,NaN,participant_relation/participant_relation.parquet,int
relative_participant_id,59,participant relation,other_participant_id,NaN,NaN,Relative participant id,Integer,NaN,NaN,Accruing,NaN,Primary,Both sexes,Single,NaN,2019-02-05,NaN,participant_relation/participant_relation.parquet,int