---
output-file: 15-ecg.html
title: 15-ecg
---

# ECG dataset  
An electrocardiogram (ECG) is a simple test that can be used to check your heart's rhythm and electrical activity. Sensors attached to the skin are used to detect the electrical signals produced by the heart each time it beats.

A resting 12-lead ECG is recorded at each visit for participants. The record length is 10 seconds and the sample rate is 1000Hz. We collect both the raw waveform ECG signal from all leads and tabular data. The tabular data are features which have been extracted automatically by the machine from the raw data such as the P wave duration.

### Data availability:
The information is stored in 2 tabular parquet files: `ecg_main.parquet`, `ecg_qc.parquet`, which contain tabular features and QC checks on the raw ECG waveform data. Mutiple time series parquet files contain the raw and processed ECG waveform data

In [ ]:
#| echo: false
import pandas as pd
pd.set_option("display.max_rows", 500)

In [ ]:
from pheno_utils import PhenoLoader

In [3]:
dl = PhenoLoader('ecg')
dl

DataLoader for ecg with
165 fields
3 tables: ['ecg_main', 'ecg_qc', 'age_sex']

In [4]:
#load in dictionary
dl.dict.head()

,field_string,description_string,parent_dataframe,relative_location,value_type,units,sampling_rate,item_type,array,cohorts,data_type,debut,pandas_dtype
tabular_field_name,,,,,,,,,,,,,
collection_date,Collection date (YYYY-MM-DD),Collection date (YYYY-MM-DD),NaN,ecg_main.parquet,Date,NaN,NaN,Auxilary,Single,10K,Tabular,2019-08-13,datetime64[ns]
timezone,Timezone,Timezone for timestamp columns,NaN,ecg_main.parquet,Categorical (single),NaN,NaN,Auxilary,Single,10K,Tabular,2019-08-13,string
collection_timestamp,Collection timestamp,Collection timestamp,NaN,ecg_main.parquet,Categorical (single),NaN,NaN,Auxilary,Single,10K,Tabular,2019-08-13,"datetime64[ns, Asia/Jerusalem]"
MDC_ECG_LEAD_I,ECG lead I,Raw ECG signal for specificed lead,raw_ecg_time_series,NaN,Time series (metrics),Microvolt,1000Hz,Data,Single,10K,Time Series,2019-08-13,int64
MDC_ECG_LEAD_II,ECG lead II,Raw ECG signal for specificed lead,raw_ecg_time_series,NaN,Time series (metrics),Microvolt,1000Hz,Data,Single,10K,Time Series,2019-08-13,int64

In [5]:
df = dl.dfs['ecg_main']