---
output-file: 5-diet_logging.html
title: 5-diet_logging
---

# Diet logging dataset  

Diet logging using a smartphone app involves collecting data on food and drink consumption through a mobile application. These data include information such as types of food, serving sizes, nutritional information and the times of consumption. The data is used to track dietary habits and can be used in scientific research to gain insights into the dietary habits of a population and to correlate to other temporal measurements and events.

### Data availability:
The information is stored in 2 parquet file: `diet_logging.parquet`, `diet_logging_events.parquet` which contain the processed and raw diet logging data respectively.

In [1]:
#| echo: false
import pandas as pd
pd.set_option("display.max_rows", 500)

In [2]:
from pheno_utils import PhenoLoader

In [3]:
dl = PhenoLoader('diet_logging')
dl

Warning: index is not unique for diet_logging_events.parquet

DataLoader for diet_logging with
21 fields
3 tables: ['diet_logging', 'diet_logging_events', 'age_sex']

# Data dictionary

In [4]:
dl.dict

,field_string,description_string,parent_dataframe,relative_location,value_type,units,sampling_rate,item_type,array,cohorts,data_type,debut,pandas_dtype
tabular_field_name,,,,,,,,,,,,,
collection_timestamp,Collection timestamp,Collection timestamp,NaN,/diet_logging/diet_logging.parquet,Time,Time,NaN,Data,Single,10K,Time Series,2019-01-29,"datetime64[ns, Asia/Jerusalem]"
collection_date,Date,Datetime column relecting the time food item w...,NaN,/diet_logging/diet_logging.parquet,Time,Time,NaN,Data,Single,10K,Time Series,2019-09-01,datetime64[ns]
logging_day,Logging day per participant,Integer indicating which day of logging period,NaN,/diet_logging/diet_logging_events.parquet,Integer,None,NaN,Data,Single,10K,Time Series,2019-09-01,int
total_logging_days,Total number of days logged,Total number of days diet was logged per resea...,NaN,/diet_logging/diet_logging.parquet,Integer,None,NaN,Data,Single,10K,Time Series,2019-09-01,int
timezone,Timezone,Timezone,NaN,/diet_logging/diet_logging.parquet,Text,None,NaN,Data,Single,10K,Time Series,2019-09-01,string
food_items,Food items,Total number of food items logged per day,NaN,/diet_logging/diet_logging.parquet,Integer,None,NaN,Data,Single,10K,Time Series,2019-09-01,int
diet_logging_events,Diet logging events,File path to diet logging events,NaN,/diet_logging/diet_logging.parquet,Text,None,NaN,Data,Single,10K,Time Series,2019-09-01,string
raw_diet_logging_events,Raw diet logging events,File path to raw diet logging events,NaN,/diet_logging/diet_logging.parquet,Text,None,NaN,Data,Single,10K,Time Series,2019-09-01,string